import { expect, test } from "bun:test";
import { readFileSync } from "node:fs";

test("ui designer page keeps the single-session shell contract", () => {
  const pageSource = readFileSync(new URL("./page.tsx", import.meta.url), "utf8");
  const shellSource = readFileSync(new URL("./components/workspace-shell.tsx", import.meta.url), "utf8");
  const railSource = readFileSync(new URL("./components/conversation-rail.tsx", import.meta.url), "utf8");
  const flowSource = readFileSync(new URL("./components/designer-flow-panel.tsx", import.meta.url), "utf8");
  const detailSource = readFileSync(new URL("./components/stage-detail-panel.tsx", import.meta.url), "utf8");
  const cssSource = readFileSync(new URL("./page.css", import.meta.url), "utf8");
  const hookSource = readFileSync(new URL("./hooks/use-ui-designer-shell-state.ts", import.meta.url), "utf8");
  const stageActionSource = readFileSync(new URL("./services/stage-action-availability.ts", import.meta.url), "utf8");
  const resolverSource = readFileSync(new URL("./services/stage-view-model-resolver.ts", import.meta.url), "utf8");
  const projectScopeFlowSource = readFileSync(new URL("./services/project-scope-flow.ts", import.meta.url), "utf8");
  const projectScopeInteractionSource = readFileSync(new URL("./services/project-scope-interaction.ts", import.meta.url), "utf8");
  const stageInteractionSource = readFileSync(new URL("./services/stage-interaction.ts", import.meta.url), "utf8");
  const composerSource = readFileSync(new URL("../chat/components/direct-session/direct-session-composer.tsx", import.meta.url), "utf8");
  const formCardSource = readFileSync(new URL("../chat/components/assistant-interaction-form-card.tsx", import.meta.url), "utf8");

  expect(pageSource).toContain("UiDesignerWorkspaceShell");
  expect(shellSource).toContain('data-testid="ui-designer-page"');
  expect(shellSource).toContain("<Splitter");
  expect(shellSource).toContain("<ConversationRail");
  expect(shellSource).toContain("<DesignerFlowPanel");
  expect(shellSource).toContain("<StageDetailPanel");
  expect(shellSource).toContain("<StageDialog");
  expect(railSource).toContain("ChatConversationPane");
  expect(railSource).toContain("重置对话");
  expect(railSource).not.toContain('data-testid="ui-designer-session-summary"');
  expect(railSource).not.toContain("工作区与对话");
  expect(railSource).not.toContain("ui-designer-session-list");
  expect(flowSource).toContain("设计包");
  expect(flowSource).not.toContain("流程 / 任务 / 清单");
  expect(flowSource).not.toContain("内置阶段");
  expect(resolverSource).toContain('title: "项目范围确认"');
  expect(resolverSource).toContain('title: "技术栈确认"');
  expect(resolverSource).toContain('title: "视觉与交互基线"');
  expect(resolverSource).toContain('title: "页面与模块确认"');
  expect(resolverSource).toContain('title: "设计规格整理"');
  expect(resolverSource.indexOf('title: "项目范围确认"')).toBeLessThan(resolverSource.indexOf('title: "技术栈确认"'));
  expect(resolverSource.indexOf('title: "技术栈确认"')).toBeLessThan(resolverSource.indexOf('title: "视觉与交互基线"'));
  expect(resolverSource.indexOf('title: "视觉与交互基线"')).toBeLessThan(resolverSource.indexOf('title: "页面与模块确认"'));
  expect(resolverSource.indexOf('title: "页面与模块确认"')).toBeLessThan(resolverSource.indexOf('title: "设计规格整理"'));
  expect(stageActionSource).toContain("重新设计");
  expect(stageActionSource).toContain("开始设计");
  expect(flowSource).toContain("isStageActionVisible");
  expect(flowSource).toContain("activeStageKey");
  expect(flowSource).toContain("pendingStageKey");
  expect(flowSource).toContain("onSelectStage");
  expect(flowSource).toContain("onStartStage");
  expect(flowSource).toContain('role="button"');
  expect(flowSource).toContain("tabIndex={0}");
  expect(flowSource).toContain("handleStageItemKeyDown");
  expect(flowSource).toContain("event.stopPropagation()");
  expect(flowSource).toContain('const pending = props.pendingStageKey === item.stageKey;');
  expect(flowSource).toContain('className={`ui-designer-stage-item${props.activeStageKey === item.stageKey ? " is-active" : ""}${pending ? " is-pending" : ""}`}');
  expect(flowSource).not.toContain("<button");
  expect(stageActionSource).toContain("继续填写");
  expect(flowSource).toContain("待填写");
  expect(flowSource).not.toContain("queueRedesignPrompt(item.key)");
  expect(flowSource).not.toContain('title: "范围确认"');
  expect(flowSource).not.toContain('title: "组件模式"');
  expect(flowSource).not.toContain('title: "布局设计"');
  expect(flowSource).not.toContain('title: "页面模板"');
  expect(flowSource).not.toContain('title: "资料补充"');
  expect(flowSource).not.toContain('title: "多语言"');
  expect(flowSource).not.toContain('title: "设计规格书"');
  expect(flowSource).toContain("ui-designer-stage-summary");
  expect(flowSource).not.toContain("summaryBlocks");
  expect(flowSource).not.toContain("ui-designer-summary-block");
  expect(flowSource).not.toContain("TextArea");
  expect(flowSource).not.toContain("保存");
  expect(flowSource).not.toContain("生成条件");
  expect(hookSource).toContain("managedExecutionEnabled: false");
  expect(hookSource).toContain("thinkingEnabled: false");
  expect(hookSource).toContain("UI_DESIGNER_CONTEXT_METADATA_KEY");
  expect(hookSource).toContain("buildProjectScopeDraft");
  expect(hookSource).toContain("buildUiDesignerStageDraft");
  expect(hookSource).toContain("parseProjectScopeJson");
  expect(hookSource).toContain("buildProjectScopeInteractionRequest");
  expect(hookSource).toContain("buildUiDesignerStageInteractionRequest");
  expect(hookSource).toContain("buildUiDesignerStageInteractionId");
  expect(hookSource).toContain("selectedSessionDetailForView");
  expect(hookSource).toContain("localProjectScopeInteraction");
  expect(hookSource).toContain("localStageInteraction");
  expect(hookSource).toContain("activeLocalInteractionRequest");
  expect(hookSource).not.toContain("const nextPendingInteractions");
  expect(hookSource).not.toContain("pendingInteractions: nextPendingInteractions");
  expect(hookSource).toContain("UI_DESIGNER_PROJECT_SCOPE_INTERACTION_ID");
  expect(hookSource).toContain("buildUiDesignerContext");
  expect(hookSource).toContain("requestStageSchema");
  expect(hookSource).toContain("requestStageResult");
  expect(hookSource).not.toContain('const schema = await requestStageSchema({');
  expect(hookSource).not.toContain("queueRedesignPrompt");
  expect(hookSource).not.toContain("previewMode");
  expect(hookSource).toContain("const sessionToHide = selectedSessionId");
  expect(hookSource).toContain("void conversationClient.hideSession(sessionToHide)");
  expect(hookSource).toContain("const stopMessage = useCallback(async () => {");
  expect(hookSource).toContain("conversationClient.stopMessage");
  expect(hookSource).toContain("void reloadDesignerState(workspaceId)");
  expect(hookSource).toContain("void reloadDesignerState(detailUpdate.detail.workspaceId)");
  expect(hookSource).toContain('normalizedStageKey === "projectScope"');
  expect(hookSource).toContain("scopeJson: stringifyProjectScope(normalized)");
  expect(hookSource).toContain("text: buildProjectScopeDraft(normalized)");
  expect(hookSource).toContain("prefillFocusBlock");
  expect(hookSource).toContain("focusBlock: composerFocusBlock");
  expect(hookSource).toContain("setDraftMessage(stageDraft)");
  expect(hookSource).toContain('normalizedInteractionId.startsWith("ui-designer:stage:")');
  expect(hookSource).toContain("submitLocalStageInteraction");
  expect(hookSource).toContain("suggestedStageKey");
  expect(hookSource).toContain("clearSuggestedStageKey");
  expect(hookSource).toContain("pendingStageKey");
  expect(hookSource).toContain("activeLocalInteractionId");
  expect(hookSource).toContain("const stageViewModels = useMemo(() => resolveStageViewModels({");
  expect(hookSource).toContain("openStageDialog");
  expect(hookSource).toContain("stageViewModels,");
  expect(cssSource).toContain(".ui-designer-rail-body .chat-direct-thread-scroll {");
  expect(cssSource).toContain("padding-right: 8px;");
  expect(cssSource).toContain("width: 6px;");
  expect(cssSource).toContain("border: 1px solid transparent;");
  expect(composerSource).toContain("className={`chat-direct-composer-token-usage is-${props.tokenBudgetUsage.status}`}");
  expect(composerSource).not.toContain("chat-direct-composer-token-usage-threshold");
  expect(shellSource).toContain("knownStageKeys");
  expect(shellSource).toContain("state.suggestedStageKey");
  expect(shellSource).toContain("state.clearSuggestedStageKey()");
  expect(shellSource).toContain("pendingStageKey={state.pendingStageKey}");
  expect(shellSource).toContain("request={state.activeLocalInteractionRequest}");
  expect(railSource).toContain("workspaceAvatarSettings={props.workspaceSettings}");
  expect(railSource).toContain("sessionSummaries={props.sessions}");
  expect(railSource).not.toContain("props.specBootstrapInteraction");
  expect(railSource).toContain("stoppingMessage={props.stoppingMessage}");
  expect(railSource).toContain("onStopMessage={() => void props.stopMessage()}");
  expect(railSource).toContain("renderStageShell={false}");
  expect(railSource).toContain('className="chat-stage"');
  expect(railSource).toContain('className="chat-session-stage-stack"');
  expect(railSource).toContain('className="chat-session-stage-host" data-active="true"');
  expect(cssSource).toContain(".ui-designer-rail-body > .chat-stage");
  expect(cssSource).toContain(".ui-designer-rail-body .chat-direct-thread-scroll::-webkit-scrollbar");
  expect(cssSource).toContain(".ui-designer-page-splitter > .ant-splitter-panel");
  expect(cssSource).toContain("display: flex;");
  expect(cssSource).toContain(".ui-designer-stage-item.is-pending");
  expect(cssSource).toContain(".ui-designer-stage-item:focus-visible");
  expect(cssSource).toContain(".ui-designer-stage-dialog-actions");
  expect(cssSource).toContain(".ui-designer-stage-form-option-grid");
  expect(projectScopeFlowSource).toContain("buildProjectScopeDraft");
  expect(projectScopeFlowSource).toContain("parseProjectScopeJson");
  expect(projectScopeFlowSource).toContain("stringifyProjectScope");
  expect(projectScopeInteractionSource).toContain("项目范围确认");
  expect(projectScopeInteractionSource).toContain("recommendedOptions");
  expect(projectScopeInteractionSource).toContain("确认范围并继续");
  expect(stageInteractionSource).toContain('kind: "select"');
  expect(stageInteractionSource).toContain('kind: "multiselect"');
  expect(stageInteractionSource).toContain('kind: "boolean"');
  expect(stageInteractionSource).toContain("buildUiDesignerStageInteractionId");
  expect(formCardSource).toContain("field.recommendedOptions");
  expect(formCardSource).toContain("chat-assistant-interaction-option-grid");
  expect(detailSource).toContain('data-testid="ui-designer-right-pane"');
  expect(detailSource).toContain("当前阶段");
  expect(detailSource).toContain('return "已完成"');
  expect(detailSource).toContain('return "待补充"');
  expect(detailSource).toContain('return "未开始"');
  expect(detailSource).not.toContain("iframe");
  expect(detailSource).not.toContain("previewMode");
});
