import { expect, test } from "bun:test";
import { readFileSync } from "node:fs";

test("ui designer page keeps the single-session shell contract", () => {
  const pageSource = readFileSync(new URL("./page.tsx", import.meta.url), "utf8");
  const shellSource = readFileSync(new URL("./components/workspace-shell.tsx", import.meta.url), "utf8");
  const railSource = readFileSync(new URL("./components/conversation-rail.tsx", import.meta.url), "utf8");
  const flowSource = readFileSync(new URL("./components/designer-flow-panel.tsx", import.meta.url), "utf8");
  const detailSource = readFileSync(new URL("./components/stage-detail-panel.tsx", import.meta.url), "utf8");
  const hookSource = readFileSync(new URL("./hooks/use-ui-designer-shell-state.ts", import.meta.url), "utf8");
  const resolverSource = readFileSync(new URL("./services/stage-view-model-resolver.ts", import.meta.url), "utf8");

  expect(pageSource).toContain("UiDesignerWorkspaceShell");
  expect(shellSource).toContain('data-testid="ui-designer-page"');
  expect(shellSource).toContain("<Splitter");
  expect(shellSource).toContain("<ConversationRail");
  expect(shellSource).toContain("<DesignerFlowPanel");
  expect(shellSource).toContain("<StageDetailPanel");
  expect(shellSource).toContain("<StageDialog");
  expect(railSource).toContain("ConversationSurface");
  expect(railSource).not.toContain("ChatConversationPane");
  expect(railSource).toContain("重置对话");
  expect(railSource).not.toContain("ui-designer-session-list");
  expect(flowSource).toContain("设计包路径");
  expect(resolverSource).toContain('title: "项目范围确认"');
  expect(resolverSource).toContain('title: "技术栈确认"');
  expect(resolverSource).toContain('title: "视觉与交互基线"');
  expect(resolverSource).toContain('title: "页面与模块确认"');
  expect(resolverSource).toContain('title: "设计规格整理"');
  expect(resolverSource.indexOf('title: "项目范围确认"')).toBeLessThan(resolverSource.indexOf('title: "技术栈确认"'));
  expect(resolverSource.indexOf('title: "技术栈确认"')).toBeLessThan(resolverSource.indexOf('title: "视觉与交互基线"'));
  expect(resolverSource.indexOf('title: "视觉与交互基线"')).toBeLessThan(resolverSource.indexOf('title: "页面与模块确认"'));
  expect(resolverSource.indexOf('title: "页面与模块确认"')).toBeLessThan(resolverSource.indexOf('title: "设计规格整理"'));
  expect(flowSource).toContain("重新设计");
  expect(flowSource).toContain("activeStageKey");
  expect(flowSource).toContain("onSelectStage");
  expect(flowSource).toContain("onStartStage");
  expect(flowSource).toContain('className={`ui-designer-stage-item${props.activeStageKey === item.stageKey ? " is-active" : ""}`}');
  expect(flowSource).not.toContain("queueRedesignPrompt(item.key)");
  expect(flowSource).not.toContain('title: "范围确认"');
  expect(flowSource).not.toContain('title: "组件模式"');
  expect(flowSource).not.toContain('title: "布局设计"');
  expect(flowSource).not.toContain('title: "页面模板"');
  expect(flowSource).not.toContain('title: "资料补充"');
  expect(flowSource).not.toContain('title: "多语言"');
  expect(flowSource).not.toContain('title: "设计规格书"');
  expect(flowSource).toContain("ui-designer-stage-summary");
  expect(flowSource).not.toContain("summaryBlocks");
  expect(flowSource).not.toContain("ui-designer-summary-block");
  expect(flowSource).not.toContain("TextArea");
  expect(flowSource).not.toContain("保存");
  expect(hookSource).toContain("managedExecutionEnabled: false");
  expect(hookSource).toContain("thinkingEnabled: false");
  expect(hookSource).toContain("UI_DESIGNER_CONTEXT_METADATA_KEY");
  expect(hookSource).toContain("buildUiDesignerContext");
  expect(hookSource).toContain("buildUiDesignerDesignSpecMarkdown");
  expect(hookSource).toContain("buildUiDesignerSourcesMarkdown");
  expect(hookSource).toContain("projectScope");
  expect(hookSource).toContain("重新确认项目范围");
  expect(hookSource).toContain("补充资料来源");
  expect(hookSource).toContain("const sessionToHide = selectedSessionId");
  expect(hookSource).toContain("void conversationClient.hideSession(sessionToHide)");
  expect(hookSource).toContain("const stopMessage = useCallback(async () => {");
  expect(hookSource).toContain("conversationClient.stopMessage");
  expect(hookSource).toContain("void reloadDesignerState(workspaceId)");
  expect(hookSource).toContain("void reloadDesignerState(detailUpdate.detail.workspaceId)");
  expect(hookSource).toContain("const stageViewModels = useMemo(() => resolveStageViewModels({");
  expect(hookSource).toContain("stageDialogState");
  expect(hookSource).toContain("openStageDialog");
  expect(hookSource).toContain("submitStageDialog");
  expect(hookSource).toContain("stageViewModels,");
  expect(railSource).toContain("workspaceAvatarSettings: props.workspaceSettings");
  expect(railSource).not.toContain("props.specBootstrapInteraction");
  expect(railSource).toContain("stoppingMessage: props.stoppingMessage");
  expect(railSource).toContain("onStopMessage: () => void props.stopMessage()");
  expect(railSource).toContain("interactionDock={controller.interactionDock}");
  expect(detailSource).toContain('data-testid="ui-designer-right-pane"');
  expect(detailSource).toContain("当前阶段");
  expect(detailSource).not.toContain("iframe");
  expect(detailSource).not.toContain("previewMode");
});
