export type {
  DesktopGitBranchItem,
  DesktopGitBranchNameInput,
  DesktopGitBranchesResult,
  DesktopGitChangeItem,
  DesktopGitChangeStatus,
  DesktopGitChangesResult,
  DesktopGitChangesSummary,
  DesktopGitCheckoutBranchInput,
  DesktopGitCommitChangesInput,
  DesktopGitCommitHashInput,
  DesktopGitCommitMessageSuggestionsQuery,
  DesktopGitCommitMessageSuggestionsResult,
  DesktopGitCommitResetMode,
  DesktopGitCompareQuery,
  DesktopGitCompareResult,
  DesktopGitCreateBranchInput,
  DesktopGitCreateTagInput,
  DesktopGitCreateWorktreeInput,
  DesktopGitCreateStashInput,
  DesktopGitDeleteBranchInput,
  DesktopGitDiscardChangesInput,
  DesktopGitHistoryDetailFile,
  DesktopGitHistoryDetailResult,
  DesktopGitHistoryQuery,
  DesktopGitHistoryResult,
  DesktopGitHistoryScope,
  DesktopGitHunkItem,
  DesktopGitHunkMutationInput,
  DesktopGitHunkSection,
  DesktopGitHunksQuery,
  DesktopGitHunksResult,
  DesktopGitIgnoreResult,
  DesktopGitModuleSnapshotQuery,
  DesktopGitModuleSnapshotResult,
  DesktopGitOperationResult,
  DesktopGitPushRemoteInput,
  DesktopGitRenameBranchInput,
  DesktopGitResetCommitInput,
  DesktopGitReviewDetailQuery,
  DesktopGitReviewDetailResult,
  DesktopGitReviewItem,
  DesktopGitReviewResult,
  DesktopGitReviewScope,
  DesktopGitRepositorySettings,
  DesktopGitSaveIgnoreInput,
  DesktopGitSaveSettingsInput,
  DesktopGitSettingsResult,
  DesktopGitRemoveWorktreeInput,
  DesktopGitStageChangesInput,
  DesktopGitStashItem,
  DesktopGitStashRefInput,
  DesktopGitStashesResult,
  DesktopGitUnstageChangesInput,
  DesktopGitWorktreeItem,
  DesktopGitWorktreesResult,
  DesktopGitGlobalSettings,
} from "./abstraction/models/desktop-git.models";
export type {
  DesktopGitCommandPort,
  DesktopGitPort,
  DesktopGitQueryPort,
} from "./abstraction/ports/desktop-git.ports";
export {
  DESKTOP_GIT_COMMAND_PORT,
  DESKTOP_GIT_PORT,
  DESKTOP_GIT_QUERY_PORT,
} from "./abstraction/tokens/desktop-git.tokens";
export { DesktopGitModule } from "./composition/git.module";
export { DesktopGitService } from "./implementation/services/desktop-git-service";
