import { join } from "node:path";

type DiscoveryDefinition = {
  source: string;
  label: string;
  envCandidates: string[];
  fallbackPaths: string[];
  strategy: string;
};

export function createSkillsDiscoveryDefinitions(userHomeDir: string): DiscoveryDefinition[] {
  return [
    {
      source: "antigravity",
      label: "Antigravity (.agent/.agents/skills)",
      envCandidates: ["ANTIGRAVITY_HOME", "AGENT_HOME", "AGENTS_HOME"],
      fallbackPaths: [
        join(userHomeDir, ".agent", "skills"),
        join(userHomeDir, ".agents", "skills"),
      ],
      strategy: "ANTIGRAVITY_HOME/AGENT_HOME/AGENTS_HOME + ~/.agent/skills + ~/.agents/skills",
    },
    {
      source: "augment",
      label: "Augment (.augment/skills)",
      envCandidates: ["AUGMENT_HOME"],
      fallbackPaths: [join(userHomeDir, ".augment", "skills")],
      strategy: "AUGMENT_HOME + ~/.augment/skills",
    },
    {
      source: "claude",
      label: "Claude Code (.claude/skills)",
      envCandidates: ["CLAUDE_HOME"],
      fallbackPaths: [join(userHomeDir, ".claude", "skills")],
      strategy: "CLAUDE_HOME + ~/.claude/skills",
    },
    {
      source: "clauda",
      label: "Clauda (.clauda/skills)",
      envCandidates: ["CLAUDA_HOME"],
      fallbackPaths: [join(userHomeDir, ".clauda", "skills")],
      strategy: "CLAUDA_HOME + ~/.clauda/skills",
    },
    {
      source: "codex",
      label: "Codex (.codex/skills)",
      envCandidates: ["CODEX_HOME"],
      fallbackPaths: [join(userHomeDir, ".codex", "skills")],
      strategy: "CODEX_HOME + ~/.codex/skills",
    },
    {
      source: "opencode",
      label: "OpenCode (.opencode/skills)",
      envCandidates: ["OPENCODE_HOME"],
      fallbackPaths: [join(userHomeDir, ".opencode", "skills")],
      strategy: "OPENCODE_HOME + ~/.opencode/skills",
    },
    {
      source: "skills_sh",
      label: "skills.sh (~/.skills)",
      envCandidates: ["SKILLS_HOME", "SKILLS_DIR"],
      fallbackPaths: [join(userHomeDir, ".skills")],
      strategy: "SKILLS_HOME/SKILLS_DIR + ~/.skills",
    },
    {
      source: "openclaw",
      label: "OpenClaw (skills)",
      envCandidates: ["OPENCLAW_SKILLS_DIR", "OPENCLAW_HOME"],
      fallbackPaths: [join(userHomeDir, "skills")],
      strategy: "OPENCLAW_SKILLS_DIR/OPENCLAW_HOME + ~/skills",
    },
    {
      source: "cline",
      label: "Cline (.cline/skills)",
      envCandidates: ["CLINE_HOME"],
      fallbackPaths: [join(userHomeDir, ".cline", "skills")],
      strategy: "CLINE_HOME + ~/.cline/skills",
    },
    {
      source: "codebuddy",
      label: "CodeBuddy (.codebuddy/skills)",
      envCandidates: ["CODEBUDDY_HOME"],
      fallbackPaths: [join(userHomeDir, ".codebuddy", "skills")],
      strategy: "CODEBUDDY_HOME + ~/.codebuddy/skills",
    },
    {
      source: "commandcode",
      label: "Command Code (.commandcode/skills)",
      envCandidates: ["COMMANDCODE_HOME"],
      fallbackPaths: [join(userHomeDir, ".commandcode", "skills")],
      strategy: "COMMANDCODE_HOME + ~/.commandcode/skills",
    },
    {
      source: "continue",
      label: "Continue (.continue/skills)",
      envCandidates: ["CONTINUE_HOME"],
      fallbackPaths: [join(userHomeDir, ".continue", "skills")],
      strategy: "CONTINUE_HOME + ~/.continue/skills",
    },
    {
      source: "cortex",
      label: "Cortex Code (.cortex/skills)",
      envCandidates: ["CORTEX_HOME"],
      fallbackPaths: [join(userHomeDir, ".cortex", "skills")],
      strategy: "CORTEX_HOME + ~/.cortex/skills",
    },
    {
      source: "crush",
      label: "Crush (.crush/skills)",
      envCandidates: ["CRUSH_HOME"],
      fallbackPaths: [join(userHomeDir, ".crush", "skills")],
      strategy: "CRUSH_HOME + ~/.crush/skills",
    },
    {
      source: "droid",
      label: "Droid (.factory/skills)",
      envCandidates: ["DROID_HOME", "FACTORY_HOME"],
      fallbackPaths: [join(userHomeDir, ".factory", "skills")],
      strategy: "DROID_HOME/FACTORY_HOME + ~/.factory/skills",
    },
    {
      source: "goose",
      label: "Goose (.goose/skills)",
      envCandidates: ["GOOSE_HOME"],
      fallbackPaths: [join(userHomeDir, ".goose", "skills")],
      strategy: "GOOSE_HOME + ~/.goose/skills",
    },
    {
      source: "junie",
      label: "Junie (.junie/skills)",
      envCandidates: ["JUNIE_HOME"],
      fallbackPaths: [join(userHomeDir, ".junie", "skills")],
      strategy: "JUNIE_HOME + ~/.junie/skills",
    },
    {
      source: "iflow",
      label: "iFlow CLI (.iflow/skills)",
      envCandidates: ["IFLOW_HOME"],
      fallbackPaths: [join(userHomeDir, ".iflow", "skills")],
      strategy: "IFLOW_HOME + ~/.iflow/skills",
    },
    {
      source: "kilocode",
      label: "Kilo Code (.kilocode/skills)",
      envCandidates: ["KILOCODE_HOME"],
      fallbackPaths: [join(userHomeDir, ".kilocode", "skills")],
      strategy: "KILOCODE_HOME + ~/.kilocode/skills",
    },
    {
      source: "kiro",
      label: "Kiro CLI (.kiro/skills)",
      envCandidates: ["KIRO_HOME"],
      fallbackPaths: [join(userHomeDir, ".kiro", "skills")],
      strategy: "KIRO_HOME + ~/.kiro/skills",
    },
    {
      source: "kode",
      label: "Kode (.kode/skills)",
      envCandidates: ["KODE_HOME"],
      fallbackPaths: [join(userHomeDir, ".kode", "skills")],
      strategy: "KODE_HOME + ~/.kode/skills",
    },
    {
      source: "mcpjam",
      label: "MCPJam (.mcpjam/skills)",
      envCandidates: ["MCPJAM_HOME"],
      fallbackPaths: [join(userHomeDir, ".mcpjam", "skills")],
      strategy: "MCPJAM_HOME + ~/.mcpjam/skills",
    },
    {
      source: "vibe",
      label: "Mistral Vibe (.vibe/skills)",
      envCandidates: ["VIBE_HOME"],
      fallbackPaths: [join(userHomeDir, ".vibe", "skills")],
      strategy: "VIBE_HOME + ~/.vibe/skills",
    },
    {
      source: "mux",
      label: "Mux (.mux/skills)",
      envCandidates: ["MUX_HOME"],
      fallbackPaths: [join(userHomeDir, ".mux", "skills")],
      strategy: "MUX_HOME + ~/.mux/skills",
    },
    {
      source: "openhands",
      label: "OpenHands (.openhands/skills)",
      envCandidates: ["OPENHANDS_HOME"],
      fallbackPaths: [join(userHomeDir, ".openhands", "skills")],
      strategy: "OPENHANDS_HOME + ~/.openhands/skills",
    },
    {
      source: "pi",
      label: "Pi (.pi/skills)",
      envCandidates: ["PI_HOME"],
      fallbackPaths: [join(userHomeDir, ".pi", "skills")],
      strategy: "PI_HOME + ~/.pi/skills",
    },
    {
      source: "qoder",
      label: "Qoder (.qoder/skills)",
      envCandidates: ["QODER_HOME"],
      fallbackPaths: [join(userHomeDir, ".qoder", "skills")],
      strategy: "QODER_HOME + ~/.qoder/skills",
    },
    {
      source: "qwen",
      label: "Qwen Code (.qwen/skills)",
      envCandidates: ["QWEN_HOME"],
      fallbackPaths: [join(userHomeDir, ".qwen", "skills")],
      strategy: "QWEN_HOME + ~/.qwen/skills",
    },
    {
      source: "roo",
      label: "Roo Code (.roo/skills)",
      envCandidates: ["ROO_HOME"],
      fallbackPaths: [join(userHomeDir, ".roo", "skills")],
      strategy: "ROO_HOME + ~/.roo/skills",
    },
    {
      source: "trae",
      label: "Trae (.trae/skills)",
      envCandidates: ["TRAE_HOME"],
      fallbackPaths: [join(userHomeDir, ".trae", "skills")],
      strategy: "TRAE_HOME + ~/.trae/skills",
    },
    {
      source: "trae_cn",
      label: "Trae CN (.trae/skills)",
      envCandidates: ["TRAE_CN_HOME", "TRAE_HOME"],
      fallbackPaths: [join(userHomeDir, ".trae", "skills")],
      strategy: "TRAE_CN_HOME/TRAE_HOME + ~/.trae/skills",
    },
    {
      source: "windsurf",
      label: "Windsurf (.windsurf/skills)",
      envCandidates: ["WINDSURF_HOME"],
      fallbackPaths: [join(userHomeDir, ".windsurf", "skills")],
      strategy: "WINDSURF_HOME + ~/.windsurf/skills",
    },
    {
      source: "zencoder",
      label: "Zencoder (.zencoder/skills)",
      envCandidates: ["ZENCODER_HOME"],
      fallbackPaths: [join(userHomeDir, ".zencoder", "skills")],
      strategy: "ZENCODER_HOME + ~/.zencoder/skills",
    },
    {
      source: "neovate",
      label: "Neovate (.neovate/skills)",
      envCandidates: ["NEOVATE_HOME"],
      fallbackPaths: [join(userHomeDir, ".neovate", "skills")],
      strategy: "NEOVATE_HOME + ~/.neovate/skills",
    },
    {
      source: "pochi",
      label: "Pochi (.pochi/skills)",
      envCandidates: ["POCHI_HOME"],
      fallbackPaths: [join(userHomeDir, ".pochi", "skills")],
      strategy: "POCHI_HOME + ~/.pochi/skills",
    },
    {
      source: "adal",
      label: "AdaL (.adal/skills)",
      envCandidates: ["ADAL_HOME"],
      fallbackPaths: [join(userHomeDir, ".adal", "skills")],
      strategy: "ADAL_HOME + ~/.adal/skills",
    },
  ];
}
