export type {
  WechatAccountConnectionStatus,
  WechatAccountStatusInput,
  WechatAccountView,
  WechatCapabilityCatalogView,
  WechatCapabilityDescriptorView,
  WechatConfigInput,
  WechatConversationBindingView,
  WechatLoginSessionView,
  WechatLoginStatus,
  WechatMediaAssetView,
  WechatMessageStatus,
  WechatProcessedMessageView,
  WechatQrLoginPollInput,
  WechatQrLoginPollResult,
  WechatQrLoginStartInput,
  WechatQrLoginStartResult,
  WechatStateView,
} from "../../../../../shared/desktop-wechat";
